"""add audit entries table

Revision ID: 0aac686ebc87
Revises: b3e7a1c9f2d4
Create Date: 2026-08-05 11:24:41.302813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0aac686ebc87'
down_revision: Union[str, Sequence[str], None] = 'b3e7a1c9f2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entries_actor_id', 'audit_entries', ['actor_id'], unique=False)
    op.create_index('ix_audit_entries_event_type', 'audit_entries', ['event_type'], unique=False)
    op.create_index('ix_audit_entries_module', 'audit_entries', ['module'], unique=False)
    op.create_index('ix_audit_entries_occurred_at', 'audit_entries', ['occurred_at'], unique=False)
    op.create_index('ix_audit_entries_resource_type', 'audit_entries', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_entries_resource_type', table_name='audit_entries')
    op.drop_index('ix_audit_entries_occurred_at', table_name='audit_entries')
    op.drop_index('ix_audit_entries_module', table_name='audit_entries')
    op.drop_index('ix_audit_entries_event_type', table_name='audit_entries')
    op.drop_index('ix_audit_entries_actor_id', table_name='audit_entries')
    op.drop_table('audit_entries')
    # ### end Alembic commands ###
