"""add analytics application health baseline and status tables

Revision ID: 2005c9dde793
Revises: 4161bf0a62eb
Create Date: 2026-08-27 15:10:41.986572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2005c9dde793'
down_revision: Union[str, Sequence[str], None] = '4161bf0a62eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_health_baselines',
    sa.Column('application', sa.Enum('FCI', 'COLORIS', 'AERO', 'VIO', name='analytics_application'), nullable=False),
    sa.Column('active_count_mean', sa.Float(), nullable=False),
    sa.Column('active_count_median', sa.Float(), nullable=False),
    sa.Column('active_count_max', sa.Float(), nullable=False),
    sa.Column('active_count_stddev', sa.Float(), nullable=False),
    sa.Column('active_count_sample_days', sa.Integer(), nullable=False),
    sa.Column('resolution_hours_mean', sa.Float(), nullable=False),
    sa.Column('resolution_hours_median', sa.Float(), nullable=False),
    sa.Column('resolution_hours_max', sa.Float(), nullable=False),
    sa.Column('resolution_hours_stddev', sa.Float(), nullable=False),
    sa.Column('resolution_hours_sample_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('application')
    )
    # Reuses the analytics_application type minted immediately above -- create_type=False so
    # this second reference does not try to CREATE TYPE it a second time (autogenerate emits a
    # plain sa.Enum(...) here by default, which would).
    op.create_table('application_health_statuses',
    sa.Column('application', postgresql.ENUM('FCI', 'COLORIS', 'AERO', 'VIO', name='analytics_application', create_type=False), nullable=False),
    sa.Column('health_level', sa.Enum('GOOD', 'WARNING', 'CRITICAL', name='analytics_health_level'), nullable=False),
    sa.Column('active_tickets', sa.Integer(), nullable=False),
    sa.Column('avg_resolution_hours', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('application')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_health_statuses')
    op.drop_table('application_health_baselines')
    # ### end Alembic commands ###
    sa.Enum(name='analytics_health_level').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='analytics_application').drop(op.get_bind(), checkfirst=True)
