"""Add permission dependencies

Revision ID: bfaa6afb4b48
Revises: f2c8a41b7d93
Create Date: 2026-08-23 14:54:24.916120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfaa6afb4b48'
down_revision: Union[str, Sequence[str], None] = 'f2c8a41b7d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_dependencies',
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('requires_permission_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('permission_id <> requires_permission_id', name='ck_permission_dependencies_not_self'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requires_permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'requires_permission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission_dependencies')
    # ### end Alembic commands ###
