"""add ticket history entries

Revision ID: fa1ffbfbe030
Revises: 4dacdcc72de1
Create Date: 2026-08-04 17:24:29.152424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fa1ffbfbe030'
down_revision: Union[str, Sequence[str], None] = '4dacdcc72de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ticket_status, ticket_priority and ticket_transfer_destination already exist as PG enum
    # types (created for the tickets table's own columns) — create_type=False here so this new
    # table reuses them instead of re-issuing a CREATE TYPE that would collide.
    op.create_table('ticket_history_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'STATUS_CHANGED', 'PRIORITY_CHANGED', 'REASSIGNED', 'TRANSFERRED', 'ARCHIVED', 'RESTORED', name='ticket_history_event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_status', postgresql.ENUM('OPEN', 'IN_PROGRESS', 'TRANSFERRED', 'RESOLVED', 'CLOSED', name='ticket_status', create_type=False), nullable=True),
    sa.Column('to_status', postgresql.ENUM('OPEN', 'IN_PROGRESS', 'TRANSFERRED', 'RESOLVED', 'CLOSED', name='ticket_status', create_type=False), nullable=True),
    sa.Column('from_priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticket_priority', create_type=False), nullable=True),
    sa.Column('to_priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticket_priority', create_type=False), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('transferred_to', postgresql.ENUM('SUPPORT_FCI', 'CONFIG_FCI', 'SUPPORT_COLORIS', 'CONFIG_COLORIS', 'AERO', 'VIO', 'EEP', 'CLIP', 'BANCO', 'ULYSSE', 'ACACIA', 'SANTAFE', 'PROXIMA', 'HABILITATION', 'DEVELOPMENT_TEAM', name='ticket_transfer_destination', create_type=False), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_history_entries')
    # ### end Alembic commands ###
