"""add jira and operational highlight ticket update support

Revision ID: fc4bcdcbdf3b
Revises: 33a907c0df89
Create Date: 2026-08-09 10:05:33.796453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4bcdcbdf3b'
down_revision: Union[str, Sequence[str], None] = '33a907c0df89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "ALTER TYPE ticket_history_event_type ADD VALUE IF NOT EXISTS 'JIRA_UPDATED';"
    )
    op.execute(
        "ALTER TYPE ticket_history_event_type ADD VALUE IF NOT EXISTS 'OPERATIONAL_HIGHLIGHT_CHANGED';"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_history_entries', sa.Column('requires_jira', sa.Boolean(), nullable=True))
    op.add_column('ticket_history_entries', sa.Column('jira_id', sa.String(), nullable=True))
    op.add_column('ticket_history_entries', sa.Column('jira_delivery_date', sa.Date(), nullable=True))
    op.add_column('ticket_history_entries', sa.Column('operational_highlight', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_history_entries', 'operational_highlight')
    op.drop_column('ticket_history_entries', 'jira_delivery_date')
    op.drop_column('ticket_history_entries', 'jira_id')
    op.drop_column('ticket_history_entries', 'requires_jira')
    # ### end Alembic commands ###
