from __future__ import annotations

from enum import StrEnum


class NotificationType(StrEnum):
	TICKET_ASSIGNED = "TICKET_ASSIGNED"
	TICKET_PRIORITY_CHANGED = "TICKET_PRIORITY_CHANGED"
	TICKET_STATUS_CHANGED = "TICKET_STATUS_CHANGED"
	COMMENT_ADDED = "COMMENT_ADDED"
	COMMENT_EDITED = "COMMENT_EDITED"
	COMMENT_DELETED = "COMMENT_DELETED"
	ATTACHMENT_ADDED = "ATTACHMENT_ADDED"
	ATTACHMENT_DELETED = "ATTACHMENT_DELETED"
	TICKET_ARCHIVED = "TICKET_ARCHIVED"
	TICKET_RESTORED = "TICKET_RESTORED"
	TICKET_TRANSFERRED = "TICKET_TRANSFERRED"
	ACCOUNT_ACTIVATED = "ACCOUNT_ACTIVATED"
	ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED"
	ROLE_ASSIGNED = "ROLE_ASSIGNED"
	ROLE_REVOKED = "ROLE_REVOKED"
	PERMISSION_GRANTED = "PERMISSION_GRANTED"
	PERMISSION_REVOKED = "PERMISSION_REVOKED"
	ROLE_PERMISSION_GRANTED = "ROLE_PERMISSION_GRANTED"
	ROLE_PERMISSION_REVOKED = "ROLE_PERMISSION_REVOKED"
	ACCOUNT_CREATED = "ACCOUNT_CREATED"
	NEW_USER_REGISTERED = "NEW_USER_REGISTERED"
