"use client"

import { useEffect, useRef, useState } from "react"
import { useQuery, useQueryClient } from "@tanstack/react-query"

import type { ChatMessage } from "@/features/chatbot/types"
import {
  createConversation,
  getConversationMessages,
  listConversations,
  sendMessage as sendMessageRequest,
  type MessageResponse,
  type PagedConversationSummary,
  type RunSummaryResponse,
} from "@/services/api/chatbot"
import { connectToAgentRunStream } from "@/services/sse/chatbot"

const chatbotConversationsQueryKey = ["chatbot", "conversations"] as const
const GENERIC_SEND_ERROR = "Une erreur est survenue. Veuillez réessayer."

function toChatMessage(message: MessageResponse): ChatMessage {
  return { id: message.id, role: message.role, content: message.content }
}

/**
 * The transcript as the reader should see it: the stored messages, with each failed run spliced in
 * straight after the user message that triggered it.
 *
 * A failed run produces no message, so replaying `messages` alone renders two user turns back to
 * back with nothing between them — the assistant appears to have ignored a question. Runs whose
 * triggering message is not on this page are dropped rather than appended: they belong to a part
 * of the thread that is not on screen, and showing them here would attach the failure to the wrong
 * question.
 */
function withFailedRuns(messages: MessageResponse[], failedRuns: RunSummaryResponse[]): ChatMessage[] {
  const byTriggeringMessage = new Map<string, RunSummaryResponse[]>()
  for (const run of failedRuns) {
    const existing = byTriggeringMessage.get(run.triggering_message_id)
    if (existing) existing.push(run)
    else byTriggeringMessage.set(run.triggering_message_id, [run])
  }

  return messages.flatMap((message) => {
    const bubble = toChatMessage(message)
    const runs = byTriggeringMessage.get(message.id)
    if (!runs) return [bubble]
    return [
      bubble,
      ...runs.map((run) => ({
        id: run.id,
        role: "ASSISTANT" as const,
        content: run.failure_reason ?? GENERIC_SEND_ERROR,
        failed: true,
      })),
    ]
  })
}

/**
 * Real chat loop for the Chatbot page, backed by the conversational_assistant module and
 * streamed via SSE. A conversation is created lazily on the first message sent. Picking an
 * existing one from ConversationsPanel loads its history and reconciles whatever the latest run
 * was doing when the page was last open — GET .../messages' `latest_run` is the catch-up path a
 * client that missed (or never opened) the SSE stream relies on: PENDING/RUNNING re-opens the
 * stream at that run, FAILED replays the same failure bubble the live path would have shown.
 *
 * `initialConversationId` is the one another page can ask for (the Dashboard's "Reprendre une
 * conversation"), opened once on mount and then forgotten — the URL is not kept in step with the
 * panel afterwards, so it opens a conversation rather than naming the current one.
 */
function useChatbot(initialConversationId?: string | null) {
  const queryClient = useQueryClient()
  const [activeConversationId, setActiveConversationId] = useState<string | null>(null)
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [isStreaming, setIsStreaming] = useState(false)
  const [isLoadingMessages, setIsLoadingMessages] = useState(false)
  const closeStreamRef = useRef<(() => void) | null>(null)
  const openedInitialConversationRef = useRef(false)

  const conversationsQuery = useQuery({
    queryKey: chatbotConversationsQueryKey,
    queryFn: () => listConversations(1, 50),
  })

  useEffect(() => {
    return () => {
      closeStreamRef.current?.()
    }
  }, [])

  function updateAssistantMessage(assistantMessageId: string, content: string) {
    setMessages((prev) =>
      prev.map((message) => (message.id === assistantMessageId ? { ...message, content } : message)),
    )
  }

  function finishStreaming() {
    setIsStreaming(false)
    closeStreamRef.current?.()
    closeStreamRef.current = null
    // Refetched on close, not only on success: a conversation's title is generated by a job that
    // is not this run, so it can land at any point — including after the stream has closed, where
    // its `conversation_title` event reaches nobody. This is the catch-up path for that case, and
    // the reason the live event is an optimisation rather than the delivery mechanism.
    queryClient.invalidateQueries({ queryKey: chatbotConversationsQueryKey })
  }

  /**
   * A generated title, applied to the conversation already on screen. Patched in place rather than
   * refetched, so the panel entry renames itself as it arrives; when the conversation is not in the
   * cached page yet (the list is still being fetched after its creation), there is nothing to patch
   * and the refetch on stream close picks it up instead.
   */
  function applyConversationTitle(conversationId: string, title: string) {
    queryClient.setQueryData<PagedConversationSummary>(chatbotConversationsQueryKey, (previous) => {
      if (!previous) return previous
      return {
        ...previous,
        items: previous.items.map((conversation) =>
          conversation.id === conversationId ? { ...conversation, title } : conversation,
        ),
      }
    })
  }

  function openStream(runId: string, assistantMessageId: string) {
    closeStreamRef.current?.()
    let content = ""
    closeStreamRef.current = connectToAgentRunStream(runId, {
      onDelta: (event) => {
        content += event.content
        updateAssistantMessage(assistantMessageId, content)
      },
      onComplete: (message) => {
        updateAssistantMessage(assistantMessageId, message.content)
        finishStreaming()
      },
      onTitle: (event) => applyConversationTitle(event.conversation_id, event.title),
      onFailed: (event) => {
        // Marked failed, not merely filled with the failure text: the bubble has to keep reading
        // as a failure after a reload, and after a reload it comes back from `failed_runs` with
        // exactly that flag.
        setMessages((prev) =>
          prev.map((message) =>
            message.id === assistantMessageId
              ? { ...message, content: event.failure_reason, failed: true }
              : message,
          ),
        )
        finishStreaming()
      },
    })
  }

  // A run still in flight when the page was last open, reconnected here as of this fetch. Only
  // PENDING/RUNNING ever reach this: a COMPLETED run's answer is already the last item in
  // `messages`, and a FAILED one arrives through `failed_runs` — rendered at the position it
  // happened rather than appended, and rendered whether or not it is the latest run.
  function reconcileLatestRun(latestRun: RunSummaryResponse | null) {
    if (!latestRun) return
    if (latestRun.status !== "PENDING" && latestRun.status !== "RUNNING") return
    const assistantMessageId = crypto.randomUUID()
    setMessages((prev) => [...prev, { id: assistantMessageId, role: "ASSISTANT", content: "" }])
    setIsStreaming(true)
    openStream(latestRun.id, assistantMessageId)
  }

  async function ensureConversation(): Promise<string> {
    if (activeConversationId) return activeConversationId
    const conversation = await createConversation()
    setActiveConversationId(conversation.id)
    return conversation.id
  }

  async function sendMessage(content: string) {
    if (!content.trim() || isStreaming) return

    setMessages((prev) => [...prev, { id: crypto.randomUUID(), role: "USER", content }])
    setIsStreaming(true)

    // The assistant bubble appears immediately, empty, and fills in live as message_delta
    // events arrive — there is no separate "thinking" placeholder outside `messages`.
    const assistantMessageId = crypto.randomUUID()
    setMessages((prev) => [...prev, { id: assistantMessageId, role: "ASSISTANT", content: "" }])

    try {
      const conversationId = await ensureConversation()
      const result = await sendMessageRequest(conversationId, content)
      queryClient.invalidateQueries({ queryKey: chatbotConversationsQueryKey })
      openStream(result.run_id, assistantMessageId)
    } catch {
      setMessages((prev) =>
        prev.map((message) =>
          message.id === assistantMessageId
            ? { ...message, content: GENERIC_SEND_ERROR, failed: true }
            : message,
        ),
      )
      setIsStreaming(false)
    }
  }

  async function selectConversation(conversationId: string) {
    if (conversationId === activeConversationId) return
    closeStreamRef.current?.()
    closeStreamRef.current = null
    setIsStreaming(false)
    setActiveConversationId(conversationId)
    setMessages([])
    setIsLoadingMessages(true)
    try {
      const result = await getConversationMessages(conversationId, 1, 200)
      setMessages(withFailedRuns(result.messages.items, result.failed_runs))
      reconcileLatestRun(result.latest_run)
    } catch {
      setMessages([
        { id: crypto.randomUUID(), role: "ASSISTANT", content: "Impossible de charger cette conversation." },
      ])
    } finally {
      setIsLoadingMessages(false)
    }
  }

  // Deliberately keyed off nothing but the id, and guarded by a ref rather than by its dependency
  // list: `selectConversation` is rebuilt on every render, so listing it would reopen the
  // conversation continuously, and a user who then picked another one would be dragged back.
  useEffect(() => {
    if (openedInitialConversationRef.current || !initialConversationId) return
    openedInitialConversationRef.current = true
    void selectConversation(initialConversationId)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialConversationId])

  function startNewConversation() {
    closeStreamRef.current?.()
    closeStreamRef.current = null
    setActiveConversationId(null)
    setMessages([])
    setIsStreaming(false)
  }

  return {
    messages,
    isStreaming,
    isLoadingMessages,
    sendMessage,
    startNewConversation,
    conversations: conversationsQuery.data?.items ?? [],
    isLoadingConversations: conversationsQuery.isPending,
    activeConversationId,
    selectConversation,
  }
}

export { useChatbot }
