from enum import StrEnum


class TicketHistoryEventType(StrEnum):
	CREATED = "CREATED"
	STATUS_CHANGED = "STATUS_CHANGED"
	PRIORITY_CHANGED = "PRIORITY_CHANGED"
	REASSIGNED = "REASSIGNED"
	TRANSFERRED = "TRANSFERRED"
	ARCHIVED = "ARCHIVED"
	RESTORED = "RESTORED"
	JIRA_UPDATED = "JIRA_UPDATED"
	OPERATIONAL_HIGHLIGHT_CHANGED = "OPERATIONAL_HIGHLIGHT_CHANGED"
